# Generated by Django 5.0.4 on 2024-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='product_name', max_length=255),
        ),
    ]
