# Generated by Django 5.0.4 on 2024-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='banners',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='type',
            name='icon',
            field=models.CharField(default='default_icon', max_length=20),
        ),
        migrations.AddField(
            model_name='type',
            name='promotional_sliders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='type',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
