# Generated by Django 5.0.4 on 2024-04-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_type_banners_type_icon_type_promotional_sliders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://picsum.photos/id/1/200/300'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='default-slug', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
