# Generated by Django 5.0.4 on 2024-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_gallery_product_image_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
